name: SneakyCosmetics
version: ${project.version}
main: com.sneaky.cosmetics.SneakyCosmetics
api-version: '1.21'
author: SneakyHub
description: A comprehensive cosmetics plugin with credits system, GUI, and tons of cosmetics!
website: https://github.com/SneakyHub/SneakyCosmetics
folia-supported: true

depend: []
softdepend: [Vault, LuckPerms, EssentialsX, PlaceholderAPI, CMI]

commands:
  sneakycosmetics:
    description: "Main unified command for all SneakyCosmetics features - access cosmetics, crates, rentals, credits, and morphs"
    usage: "/<command> <cosmetics|crate|rental|credits|morph|help|info|reload> [subcommand] [args...]"
    aliases: [sc, sneaky]
    permission: sneakycosmetics.use
    permission-message: "&cYou don't have permission to use SneakyCosmetics!"
  
  cosmetics:
    description: "Browse, equip, and manage your cosmetic collection including particles, hats, pets, trails, gadgets, wings, and auras"
    usage: "/<command> [help|list|toggle|give|remove|clear|reload|update|debug] [player] [cosmetic]"
    aliases: [cosmetic, cosm]
    permission: sneakycosmetics.use
    permission-message: "&cYou don't have permission to use cosmetics!"
  
  credits:
    description: "Manage your credit balance - buy, earn, spend, and transfer credits for purchasing cosmetics"
    usage: "/<command> [balance|buy|give|remove|set|daily|top|help] [player] [amount]"
    aliases: [credit, money]
    permission: sneakycosmetics.credits
    permission-message: "&cYou don't have permission to use the credits system!"
  
  crate:
    description: "Open mystery crates to unlock random cosmetics and rewards with different rarity levels"
    usage: "/<command> [open|buy|list|info|give|help] [type] [quantity] [player]"
    aliases: [crates, cratebox]
    permission: sneakycosmetics.use
    permission-message: "&cYou don't have permission to use crates!"
  
  rental:
    description: "Rent cosmetics temporarily for a lower cost - perfect for trying before buying permanently"
    usage: "/<command> [rent|extend|list|info|browse|help] [cosmetic] [duration]"
    aliases: [rent, cosmeticrental]
    permission: sneakycosmetics.use
    permission-message: "&cYou don't have permission to use the rental system!"
  
  morph:
    description: "Transform into different creatures and entities with unique abilities and special powers"
    usage: "/<command> [transform|unmorph|list|info|ability|check|menu|top|help] [morph_name] [player]"
    aliases: [transform, shift]
    permission: sneakycosmetics.use
    permission-message: "&cYou don't have permission to use morphs!"

permissions:
  sneakycosmetics.*:
    description: All SneakyCosmetics permissions
    children:
      sneakycosmetics.use: true
      sneakycosmetics.credits: true
      sneakycosmetics.admin: true
      sneakycosmetics.vip: true
      sneakycosmetics.premium: true
    default: op
  
  sneakycosmetics.use:
    description: Use basic cosmetics features
    default: true
  
  sneakycosmetics.credits:
    description: Use credits system
    default: true
  
  sneakycosmetics.admin:
    description: Admin commands and management
    default: op
  
  sneakycosmetics.vip:
    description: Access to VIP cosmetics
    default: false
  
  sneakycosmetics.premium:
    description: Access to premium cosmetics
    default: false
  
  sneakycosmetics.bypass:
    description: Bypass cosmetic restrictions
    default: op